name: Weekly CTF Update

on:
  schedule:
    - cron: '0 12 * * 4'
  workflow_dispatch:

jobs:
  Weekly-Update:
    name: Weekly Update
    environment: libbabel.so
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v6

      - name: Execute action
        uses: ./
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          window_size: 4
          message_content: <@&1381971729680961566>
          app_username: Watch Doggo
          app_avatar: https://i.imgur.com/cuEp3vr.gif
          embed_color: 11845374
          footer_text: Doggo fetched everything very fast
          footer_icon: https://i.imgur.com/cuEp3vr.gif
          filter_online: true
